import type { APIRoute } from "astro";
import { site } from "~/data/site";

/**
 * robots.txt — generated from site config so the sitemap host stays in sync
 * with astro.config.mjs `site`. Allows everything by default; AI crawlers
 * are intentionally allowed (citation in AI assistants is free distribution
 * for a coach's personal practice).
 *
 * To deny a path, add it to the Disallow list and re-deploy.
 */
export const GET: APIRoute = () => {
  const body = `# robots.txt for ${site.brand}
# Generated by src/pages/robots.txt.ts. Edit there, not here.
# AI crawlers are intentionally allowed — flip to Disallow if priorities change.

User-agent: *
Allow: /
Disallow: /thanks
Disallow: /og/
Disallow: /404

Sitemap: ${site.domain}/sitemap-index.xml
`;
  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
};
